### ISSUE TITLE
Support for readable body

### ISSUE THREAD

**Issue by go-cristian** [go-cristian/HttpTestRecordIntereptor#3]
👋  @felipeska, has this moved to use `ByteArray`, the body is no longer "human" readable (at the files). Could it be a good option to record this a string sometimes? How the API can look?

**Comment by felipeska** [comment]
hey @go-cristian I think this offers more flexibility, it is also possible to consider a next version that allows to convert the body to a string depending on the content-type or download it if it is a file, it all depends of the _vision or goal of the library_
